version: '3.8'

services:
  micro_cursos:
    build:
      context: ./micro_cursos
    ports:
      - "8002:8002"  # Exponer el puerto de micro_cursos
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/micro_cursos_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    networks:
      - micro_network

  micro_asignatura:
    build:
      context: ./micro_asignatura
    ports:
      - "8081:8081"  # Exponer el puerto de micro_asignatura
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/micro_asignatura_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db
    networks:
      - micro_network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro_cursos_db
    ports:
      - "3306:3306"
    networks:
      - micro_network

networks:
  micro_network:
    driver: bridge
